### PR TITLE
Upgrade to NetStandard 2.0

### LINKED ISSUE #17: Upgrade to .NetStandard 2.0
In line with other toolkits close to the core.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #17 - second attempt.

I opted to take the same approach as for [the SQL Toolkit PR](https://github.com/BHoM/SQL_Toolkit/pull/38) to handle the lack of compatibility needed with Grasshopper highlighted in the first attempt in #18.

### Test files

1. Install a recent alpha or the 6.1 beta (either works).
2. Delete `Excel_Adapter.dll`, `Excel_Engine.dll`, and `Excel_oM.dll` from your local assemblies
3. Compile in `debug` mode - this should give you the same DLLs as the installer
4. Run test scripts of your choosing - these should run successfully without errors
5. Compile in `ZeroCodeTool` mode - this should give you a new output folder in the `Excel_Toolkit/Build` location
6. Hmm - how to test this bit?!?
7. I'd recommend making a new `.Net6` project, referencing the DLLs and try to pull some data replicating a script used in step 4. Providing the code compiles without compiler warnings (compiler warnings should relate to trying to use `.NetFramework` in `.Net` environments - these should NOT appear with this work) and data can be pulled into a console, this should be sufficient?

[Excel_Toolkit_Test.zip](https://github.com/BHoM/Excel_Toolkit/files/11309690/Excel_Toolkit_Test.zip)

But same as SQL_Toolkit, I'm a bit kind - this zip file should help with testing steps 6 onwards - it contains a `.Net6` solution with references to the right DLLs/nugets that would come if the `NetStandard` adapter was included via a nuget (the ultimate end result for this work). You will need to reference the `Excel_Adapter`, `Excel_Engine`, and `Excel_oM` from your local build of `Excel_Toolkit/Build/netstandard2.0` folder - but the other DLLs are already hardcoded for `C:/ProgramData/BHoM` so hopefully minimal set up needed! You will need to update line 11 to your directory if you do use this. You can also set it up to pull data from other sheets in addition to the test one I've included.

Also feel free to not use this - but it's what I made to help debug/run through my own testing instructions so figured I might as well share it! 😄 

### Additional comments

Other work to be included for audit as to how this approach ended up being picked:
PR #18

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-complianced

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 12972870256

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance
@BHoMBot check core

**Review by adecler — APPROVED** [review]
I cannot really contribute much about the change in `VerifySecurityEvidenceForIsolatedStorage` as I was not really involved into that.
But, otherwise, the code changes make sense and all is working well when going through the steps described in the original message.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
