### PR TITLE
Upgrade to .NetStandard 2.0

### LINKED ISSUE #17: Upgrade to .NetStandard 2.0
In line with other toolkits close to the core.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #17 

Please test carefully - this one included an update/change because of items used between .Net Framework and .Net Standard.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 12028323176

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Review by adecler — CHANGES_REQUESTED** [review]
Probably needs a file copy:

image

**Comment by alelom** [comment]
Worth noting this is [the same exception we get in File_Toolkit](https://github.com/BHoM/File_Toolkit/pull/152#issuecomment-1474159201). Also worth noting that in that case the exception is thrown when the Adapter is used within Rhino, not from Unit tests.

**Pull request closed without merging**
