### PR TITLE
Excel adapter fixed to allow for enum values

### LINKED ISSUE #14: Excel adapter leaves the sheet empty if inputs contain enum values
#### Description:

As in the title, if any property of an object pushed to Excel is of enum type, the data will not be pushed.

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/3020
   
### Issues addressed by this PR

Closes #14

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by adecler — CHANGES_REQUESTED** [review]
For Enum, it is better to use `IToText` so it makes use of the `DisplayText` attribute.
Given that `IToText` needs to be improve to support primitives, I woudl suggest something like this for now: `y => y is Enum ? y.IToText() : y.ToString()` (to be tested)
Unless, you want to fix the `IToText` for primitives of course 😄

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Review by adecler — APPROVED** [review]
Works well for me.
I have noticed some issue when `goDeep` is set to true but this is unrelated to this PR so I have raised a separate issue (https://github.com/BHoM/Excel_Toolkit/issues/16) and will fix once this one is merged

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling

**Pull request merged**
