### PR TITLE
Excel_Toolkit: Improved UX for adapter pull

### LINKED ISSUE #37: Improve UX for adapter pull
Currently there are two CellContentsRequest components, removing one of them and making sure the other has the same behaviour would improve UX.

### PR DESCRIPTION
**Pull request by albinber**
### Issues addressed by this PR

Closes #37

### CODE REVIEW

**Comment by albinber** [comment]
@bhombot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
UX is improved with less options to confuse users with, great find @albinber

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
