### PR TITLE
Migrate over Adapter related files from original Excel_Toolkit (now Excel_UI)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/Excel_UI/pull/348

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by adecler — APPROVED** [review]
All the files removed from Excel_Toolkit can be found here.
The code compiles without error.
The overall way the files were split matches the requirement from the raised issue

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning

**Pull request merged**
