### PR TITLE
Remove unnecessary using which is preventing ZeroCodeTool build

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes issue where ZeroCodeTool config cannot build for Nugets

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by CKBoulter — APPROVED** [review]
File changes resolves issue where ZeroCodeTool config cannot build for Nugets.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 20506745722

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer, null-handling, serialisation, ready-to-merge, versioning

**Pull request merged**
