### PR TITLE
Add versioning for ExcelPushConfig

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes an issue with versioning from #5 which was missed by the bot.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
PreviousVersion attributes correctly applied. Approved

**Pull request merged**
