### PR TITLE
Add ability to pull worksheet names from an Excel workbook

### LINKED ISSUE #27: Add ability to get all worksheets from a given Excel file
Useful for if you don't know what worksheets you have.

Provide a `WorksheetRequest` and return as a `List<string>` all the worksheet names from that workbook.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #27 

### Test files
Available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FExcel%5FToolkit%2F%2328%2DWorksheetNames&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b) - a GH file and an Excel file linked to test with.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by desaiwangBH — APPROVED** [review]
Great! Tested with my own file and I like the search function, especially as it is case insensitive :)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
