### PR TITLE
Fix the duplicate dependency in the nuspec file

### LINKED ISSUE #82: NuGet package failed to create
#### Description:
This PR broke the nuget spec file by adding a duplicate of dependency: https://github.com/BHoM/Excel_Toolkit/pull/72

image

image

#### Steps to reproduce:
Try to create a nuget package for Excel

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #82

See issue for more details. 

@pawelbaran, I was not too sure who else to add as a  reviewer. It is a fairly straight forward fix but happy to jump in a call if you need more details.

### CODE REVIEW

**Review by pawelbaran — APPROVED** [review]
Change makes sense - the code builds and still works, duplicate removed. Happy to approve!

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
