### PR TITLE
ClosedXML Version Updated

### LINKED ISSUE #57: ClosedXML version issue causing crashing when using export to excel in dependent toolkits
#### Description:

Related: https://github.com/BHoM/PowerPoint_Toolkit/issues/8

ClosedXML uses DocumentFormat.OpenXML

Excel_Adapter uses DocumentFormat.OpenXML

PowerPoint_Adapter uses DocumentFormat.OpenXML

Dependent on build order and specified version, the correct assembly may not be loaded.

### PR DESCRIPTION
**Pull request by travispotterBH**
### Issues addressed by this PR

Closes #57

### CODE REVIEW

**Comment by travispotterBH** [comment]
@BHoMBot check core
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on [this review](https://github.com/BHoM/PowerPoint_Toolkit/pull/12#pullrequestreview-1829449442)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
