### PR TITLE
Update nuget package to match PowerPoint Toolkit

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes https://github.com/BHoM/PowerPoint_Toolkit/issues/8

### Test files
Test both Excel Toolkit and PowerPoint Toolkit - [this PowerPoint PR](https://github.com/BHoM/PowerPoint_Toolkit/pull/2) from @adecler has a decent test script for testing PowerPoint Toolkit.

Test pulling and pushing information to/from Excel and the test script for PowerPoint Toolkit.

### CODE REVIEW

**Review by Tom-Kingstone — APPROVED** [review]
Tested Powerpoint_Toolkit using the test script provided, and the output Powerpoint is as expected. Also tested Excel pulling and pushing, and was working as expected.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
